### ISSUE TITLE
it is not performing

### ISSUE THREAD

**Issue by prokarm19** [Askedio/laravel-soft-cascade#87] opened 2018-10-15 06:07 UTC
thank you beforehand !
i have defined all the process which you have told but still it is not cascading the softdelete 
i have parent model
  <?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Askedio\SoftCascade\Traits\SoftCascadeTrait;

class File extends Model
{
  use SoftDeletes;
  protected $primaryKey = 'F_id';
  protected $dates = ['deleted_at'];
  protected $softCascade = ['entries','Countries'];

  public function entries(){
  return   $this->hasMany('App\Range');
  }

  public function Countries(){
  return   $this->hasMany('App\Country');
  }
}

the  child model are::

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Askedio\SoftCascade\Traits\SoftCascadeTrait;

class Range extends Model
{
  use SoftDeletes;
  protected $primaryKey = 'Per_id';
  protected $dates = ['deleted_at'];
  protected $softCascade = ['prihscodes'];

    public function file(){
      return $this->belongsTo('App\File','pri_file_F_id');
    }

    public function prihscodes(){
      return $this->hasMany('App\Hscode');
    }
}

  public function principleTrash($id){
       $delete_file= File::find($id);
       $delete_file->where('F_id',$id)->first()->delete();
       return redirect()->back();
    }

**Comment by maguilar92** [comment] 2018-10-15 06:21
@prokarm19 Please send the issue formated well. Please add this information:

- Laravel Soft Cascade Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:


### Steps To Reproduce:

**Comment by maguilar92** [comment] 2018-11-16 10:13
@prokarm19 Due to the time that has passed without receiving an answer, I proceed to close the issue. In case it keeps happening you can reopen it at any time with the information we request.

**Closed as completed by maguilar92** 2018-11-16 10:13 UTC
